name: Generate snake animation

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    paths:
      - ".github/workflows/snake.yml" # Run any time this file is modified

  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: push snake.svg to the profile directory
        run: |
          cp dist/snake.svg profile/snake.svg
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile/snake.svg
          git commit -m "chore: update snake.svg"
          git push
